#!/bin/sh

self_dir=$(dirname $(readlink -f $0));
# echo $self_dir;
# set -x

arch=$(uname -m);

if [ $arch = "i686" ] ; then
    $self_dir/clang-complete32 -v $@
else
    $self_dir/clang-complete64 -v $@
fi
